name = "roteamento-coletas-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "roteamento-coletas-backend-prod"
route = "api.samuelchaves.com/*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "roteamento-coletas-db"
database_id = "02caf3be-72a5-4832-9e8f-77b86172c9fd"

[env.staging]
name = "roteamento-coletas-backend-staging"
route = "staging-api.samuelchaves.com/*"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "roteamento-coletas-db"
database_id = "02caf3be-72a5-4832-9e8f-77b86172c9fd"

[triggers]
crons = ["0 0 * * *"] # Daily at midnight for cleanup tasks
