# CONFIGURAÇÃO PARA AMBIENTE DE HOMOLOGAÇÃO
# ===========================================
# Este arquivo é carregado quando o perfil 'homo' está ativo
# Configurações para testes de homologação (ambiente similar à produção)

spring:
  # Configurações do banco de dados PostgreSQL (homologação)
  datasource:
    # URL de conexão com o PostgreSQL
    # Formato: jdbc:postgresql://host:porta/nome_banco
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:srpc_homo}?useSSL=false&serverTimezone=UTC&allowUnicode=true&characterEncoding=UTF-8
    # Nome do usuário do banco de dados (variável de ambiente)
    username: ${DB_USERNAME:postgres}
    # Senha do banco de dados (variável de ambiente)
    password: ${DB_PASSWORD:postgres}
    # Driver JDBC do PostgreSQL
    driver-class-name: org.postgresql.Driver
    
    # Configurações de pool de conexões para homologação
    hikari:
      # Número máximo de conexões no pool
      maximum-pool-size: ${DB_MAX_POOL_SIZE:15}
      # Número mínimo de conexões no pool
      minimum-idle: ${DB_MIN_POOL_SIZE:3}
      # Tempo máximo de vida de uma conexão (em milissegundos)
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      # Tempo máximo de espera por uma conexão (em milissegundos)
      connection-timeout: 30000
      # Tempo de inatividade antes de fechar uma conexão (em milissegundos)
      idle-timeout: 600000
      # Teste de conexão antes de usar
      connection-test-query: SELECT 1
    
  # Configurações do JPA/Hibernate para homologação
  jpa:
    # Hibernate como implementação do JPA
    hibernate:
      # Estratégia de criação das tabelas para homologação
      # update: atualiza as tabelas existentes (seguro para homologação)
      ddl-auto: update
    # Mostrar queries SQL para debugging de homologação
    show-sql: true
    # Formatar queries SQL para melhor legibilidade
    format-sql: true
    # Configurações específicas do Hibernate para homologação
    properties:
      hibernate:
        # Dialeto SQL do PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Configurações de performance para homologação
        jdbc:
          batch_size: ${HIBERNATE_JDBC_BATCH_SIZE:30}
        # Configurações de cache para homologação
        cache:
          use_second_level_cache: ${HIBERNATE_CACHE_ENABLED:true}
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        # Configurações de estatísticas para homologação
        generate_statistics: true
        # Configurações de sessão para homologação
        session:
          events:
            log: true

# Configurações de logging para homologação
logging:
  level:
    # Nível geral da aplicação (mais verboso para homologação)
    root: ${LOG_LEVEL:INFO}
    # Nível específico para o pacote da aplicação
    br.com.roteamento: ${SPRING_LOG_LEVEL:DEBUG}
    # Logar queries SQL para homologação
    org.hibernate.SQL: ${HIBERNATE_LOG_LEVEL:DEBUG}
    # Logar parâmetros das queries para homologação
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_LOG_LEVEL:DEBUG}
    # Log de transações para homologação
    org.springframework.transaction: DEBUG
  # Padrão de formatação dos logs para homologação
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # Configuração para arquivo de log
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # Configuração de arquivo de log para homologação
  file:
    name: logs/srpc-homo.log
    max-size: 100MB
    max-history: 30

# Configurações específicas para homologação
app:
  # Configurações de roteamento para homologação
  routing:
    # Raio máximo de busca para coletas (em metros) - similar à produção
    max-search-radius: ${ROUTING_MAX_SEARCH_RADIUS:8000}
    # Tempo máximo de espera para cálculo de rota (em segundos) - similar à produção
    max-routing-time: ${ROUTING_MAX_TIME:45}
  # Configurações de notificação para homologação
  notification:
    # Tempo de expiração de notificações (em minutos) - similar à produção
    expiration-time: ${NOTIFICATION_EXPIRATION_TIME:45}
    # Máximo de tentativas de envio - similar à produção
    max-retry-attempts: ${NOTIFICATION_MAX_RETRY_ATTEMPTS:4}
  
  # CONFIGURAÇÕES DE LOCALIZAÇÃO PARA HOMOLOGAÇÃO - BELO HORIZONTE
  location:
    # Coordenadas padrão para testes de homologação (Belo Horizonte)
    default:
      latitude: -19.9167
      longitude: -43.9345
      cidade: "Belo Horizonte"
      estado: "MG"
      regiao: "Grande Belo Horizonte"
    
    # Pontos de referência para testes de roteamento
    pontos-teste:
      centro:
        nome: "Centro de Belo Horizonte"
        latitude: -19.9167
        longitude: -43.9345
        endereco: "Praça Sete de Setembro, Centro, Belo Horizonte - MG"
      
      savassi:
        nome: "Savassi"
        latitude: -19.9208
        longitude: -43.9376
        endereco: "Rua Pernambuco, Savassi, Belo Horizonte - MG"
      
      pampulha:
        nome: "Pampulha"
        latitude: -19.8519
        longitude: -43.9695
        endereco: "Avenida Antônio Abrahão Caram, Pampulha, Belo Horizonte - MG"
      
      barreiro:
        nome: "Barreiro"
        latitude: -19.9667
        longitude: -44.0167
        endereco: "Rua Padre Eustáquio, Barreiro, Belo Horizonte - MG"
      
      venda-nova:
        nome: "Venda Nova"
        latitude: -19.8167
        longitude: -43.9500
        endereco: "Avenida Venda Nova, Venda Nova, Belo Horizonte - MG"
      
      contagem:
        nome: "Contagem"
        latitude: -19.9333
        longitude: -44.0500
        endereco: "Centro de Contagem, Contagem - MG"
      
      betim:
        nome: "Betim"
        latitude: -19.9667
        longitude: -44.2000
        endereco: "Centro de Betim, Betim - MG"
      
      ibirite:
        nome: "Ibirité"
        latitude: -20.0167
        longitude: -44.0667
        endereco: "Centro de Ibirité, Ibirité - MG"

# Configurações de gerenciamento para homologação
management:
  endpoints:
    web:
      exposure:
        # Mais endpoints expostos para homologação
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,env,configprops}
        # Endpoints sensíveis NÃO expostos em homologação
        exclude: beans,shutdown
  # Configurações de métricas para homologação
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}
    # Configurações de coleta de métricas
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

  # Configurações de segurança para homologação
  security:
    # Configurações do JWT para homologação
    jwt:
      # Chave secreta para assinar os tokens JWT (deve ser uma variável de ambiente)
      secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      # Tempo de expiração do token (24 horas em milissegundos)
      expiration: ${JWT_EXPIRATION:86400000}
