# CONFIGURAÇÃO PARA AMBIENTE DE TESTE
# =====================================
# Este arquivo é carregado quando o perfil 'test' está ativo
# Ideal para testes automatizados e CI/CD

# Configurações do servidor para teste
server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /test

spring:
  # Configurações do banco de dados H2 (teste)
  datasource:
    # URL de conexão com o H2 em memória
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # Nome do usuário do banco de dados H2
    username: sa
    # Senha do banco de dados H2
    password: 
    # Driver JDBC do H2
    driver-class-name: org.h2.Driver
    
    # Configurações de pool de conexões para teste
    hikari:
      # Número máximo de conexões no pool
      maximum-pool-size: 5
      # Número mínimo de conexões no pool
      minimum-idle: 1
      # Tempo máximo de vida de uma conexão (em milissegundos)
      max-lifetime: 600000
      # Tempo máximo de espera por uma conexão (em milissegundos)
      connection-timeout: 10000
    
  # Configurações do JPA/Hibernate para teste
  jpa:
    # Hibernate como implementação do JPA
    hibernate:
      # Estratégia de criação das tabelas para teste
      # create-drop: recria as tabelas a cada execução e as remove ao final
      ddl-auto: create-drop
    # Mostra as queries SQL no console (útil para teste)
    show-sql: true
    # Formata as queries SQL para melhor legibilidade
    # format-sql: true  # Propriedade não reconhecida pelo Spring Boot 3.x
    # Configurações específicas do Hibernate para teste
    properties:
      hibernate:
        # Dialeto SQL do H2
        dialect: org.hibernate.dialect.H2Dialect
        # Configurações de performance para teste
        jdbc:
          "[batch_size]": 5
        # Configurações de cache para teste
        cache:
          "[use_second_level_cache]": false
        # Log de queries SQL com parâmetros (teste)
        type:
          descriptor:
            sql:
              trace: true

  # Configurações de segurança para teste
  # security:  # Propriedade customizada - funciona normalmente
    # Configurações do JWT para teste
    # jwt:  # Propriedade customizada - funciona normalmente
      # Chave secreta para teste (NÃO usar em produção)
      secret: test-secret-key-for-testing-only-not-for-production-use
      # Tempo de expiração do token (1 hora em milissegundos)
      expiration: 3600000
      # Tempo de expiração do refresh token (24 horas em milissegundos)
      refresh-token:
        expiration: 86400000

# Configurações de logging para teste
logging:
  level:
    # Nível geral da aplicação
    root: ${LOG_LEVEL:WARN}
    # Nível específico para o pacote da aplicação
    "[br.com.roteamento]": ${SPRING_LOG_LEVEL:INFO}
    # Nível para queries SQL (teste)
    "[org.hibernate.SQL]": ${HIBERNATE_LOG_LEVEL:WARN}
    # Nível para parâmetros das queries (teste)
    "[org.hibernate.type.descriptor.sql.BasicBinder]": ${HIBERNATE_LOG_LEVEL:WARN}
    # Log de transações (teste)
    "[org.springframework.transaction]": WARN
  # Padrão de formatação dos logs para teste
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configurações específicas para teste
# app:  # Propriedade customizada - funciona normalmente
  # Configurações de roteamento para teste
  # routing:  # Propriedade customizada - funciona normalmente
  #   max-search-radius: ${ROUTING_MAX_SEARCH_RADIUS:1000}
  #   max-routing-time: ${ROUTING_MAX_TIME:10}
  # Configurações de notificação para teste
  # notification:  # Propriedade customizada - funciona normalmente
  #   expiration-time: ${NOTIFICATION_EXPIRATION_TIME:5}
  #   max-retry-attempts: ${NOTIFICATION_MAX_RETRY_ATTEMPTS:1}

# Configurações de gerenciamento para teste
management:
  endpoints:
    web:
      exposure:
        # Endpoints expostos para teste
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}
  # Configurações de métricas para teste
  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_ENABLED:false}

# Configurações de cache para teste
  # cache:  # Propriedade customizada - funciona normalmente
  #   type: simple
  #   cache-names:
  #     - materiais
  #     - usuarios
  #     - rotas